### ISSUE TITLE
Current versions not detected

### ISSUE THREAD

**Issue by truthsword** [rzander/ruckzuck#103]
When I launched RZ today. I was again greeted by the TOS screen, and after allowing that, I was notified of 14 apps with updates. However **many of these updates I had declined previously**, and again I marked these 'ignore'.

Also... I had two apps showing available updates **that I had previously installed**, while RZ said that I had an older version. Coincidentally, I had submitted updates for these apps in the past, if that is a factor.

Why would either of these occur?

**Comment by rzander** [comment]
The declined updates are store in you user profile (%localappdata%\zander_tools)...  Maybe you run a cleanup or you have updated to a newer version of ruckzuck.exe ...

Which two apps are showing an update ? If the apps do not have a valid version number format then it's by design that everything that does not match the current version in ruckzuck will be showed as update.
