### ISSUE TITLE
skip/exclude updates

### ISSUE THREAD

**Issue by kevlar8441** [rzander/ruckzuck#104]
Hi Support,
im using RZGet and need to exclude teamviewer from updating as im only licenced to 9.0. What command could i use to exclude this application?
Regards,
Kevin

**Comment by rzander** [comment]
good point ! will add an option to exclude specific products from update....

**Comment by rzander** [comment]
I'm planning on optione like
```
 RZGet.exe update --all --exclude <Shortname1>[;<Shortname2>]
```
This would allow to specify some exludes... would this fullfill your requirements as well ?

**Comment by kevlar8441** [comment]
that would be perfect, thank you for the quick responce

**Comment by rzander** [comment]
a Pre-Release Version is available at: https://github.com/rzander/ruckzuck/releases/tag/1.7.1.7

code change: https://github.com/rzander/ruckzuck/commit/af2fe95cbefd5884d3d7b3e291f91ea2a17cf3ee

**Comment by kevlar8441** [comment]
Hi Roger,
Thanks for the quick responce and will test today. Do you have a paypal link i can donate to as im loving this service compared to other companies i have delt with for software patching. 
Regards,
Kevin

**Comment by rzander** [comment]
There should be a "Sponsor" button on the right upper corner... Otherwise: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=L6DHFJL7GT3UU&source=url ... RuckZuck is part of the commercial service of https://romawo.com, that's why the donation will go into this pocket...

Note for the exclude parameter. if you have names with a space, add brackets on the complete exclude string like:
```
 RZGet.exe update --all --exclude "Shortname A;Shortname B;Shortname C"
```

**Comment by vertigo220** [comment]
Could you add this to the GUI as well? Ideally, there should be a "Skip All Updates" or "Ignore App" or "Ignore Updates" in the context menu in both the install and update screens.
