### ISSUE TITLE
Update for OneGet Provider

### ISSUE THREAD

**Issue by einbjoern** [rzander/ruckzuck#191]
Hi Roger,
we are using the oneget provider and have the signature issue fixed with rzget version 1.7.2.5
will there be an update for the oneget provider as well?
The latest oneget version I could find was 1.7.2.1

best regards,
Björn.

**Comment by rzander** [comment]
Hi Björn,
There is no further development planned on the OneGet Provider from my side, but it's OpenSource... maybe "someone else" will fix it... 

The Issue with the signature is not fixed in 1.7.2.5; RuckZuck does just not verify the full signature, only the hash of the file... If you are affected from this Issue, something is wrong with your OS as the OS does not trust the signature of the downloaded Files. Check if you have all OS updates installed and windows is able to update the CTL (trusted certificate list) -> http://woshub.com/updating-trusted-root-certificates-in-windows-10/
