### ISSUE TITLE
RZ for ConfigMgr does creates entry application but does not download package or create deployment type

### ISSUE THREAD

**Issue by doralsoral** [rzander/ruckzuck#193]
The last time I went into the RZ menu from CM it showed about 4 of my apps needed updating so I ran it like i normally do. After it was done none of those apps had a deployment type. I went to look in my content source and noticed none of the new apps were even downloaded. This also includes any new applications I have never deployed with RZ. I have uninstalled/reinstalled RZ and made a new config file from scratch. Not sure where else to start troubleshooting. Are there any log files I could start looking at?

**Comment by rzander** [comment]
The reason is because RZ4CM is using an outdated API... I have created a fixed version on: https://github.com/rzander/ruckzuck/releases/tag/1.7.2.5

I do not have a ConfigMgr Site available, so if you can try to replace the RZ4CM.exe (make a backup of the old exe and .config)

**Comment by doralsoral** [comment]
> The reason is because RZ4CM is using an outdated API... I have created a fixed version on: https://github.com/rzander/ruckzuck/releases/tag/1.7.2.5
> 
> I do not have a ConfigMgr Site available, so if you can try to replace the RZ4CM.exe (make a backup of the old exe and .config)

So I just replaced the .exe in the install folder. Initially it gave me a prompt where i had to click run unless i unchecked the box to ask everytime. After I unchecked it I got one prompt from SCCM to allow changes to the computer. After that even after restarting the CM console when I try to launch RZ from the console the UI never pops up. It is running in the background and I have to end it in task manager.

**Comment by rzander** [comment]
ok, seems to be more complicated... I have to spin up an SCCM Environment---

**Comment by rzander** [comment]
I have update the RZ4CM.exe on https://github.com/rzander/ruckzuck/releases/tag/1.7.2.5
Can you try it again...  at least on my test site it's working now...

**Comment by doralsoral** [comment]
> I have updated the RZ4CM.exe on https://github.com/rzander/ruckzuck/releases/tag/1.7.2.5 Can you try it again... at least on my test site it's working now...

Yes this one works. Thanks very much

**Comment by grantemsley** [comment]
I can also confirm that it's working, but there may be a couple bugs still.

- If there are multiple old versions of an app, the update list is showing the oldest installed version under "Old version". Pretty sure it used to show the newest installed version there. eg. I have previously created applications for Chrome 101 and Chrome 103, and for the Chrome 104 update it's showing 101 as the old version.
- At least one app (Google Chrome 104.0.5112.102) got created with it's optional reference set to "RZ0" instead of the usual SWId value. I deleted the app and recreated it and got the same results. This seems to break detection, because running the import tool doesn't detect Chrome 104 as being installed and still offers it as an update. Looking at the catalog there seem to be 29 applications reporting a SWId of 0.

**Comment by rzander** [comment]
Now I remember why I have not touched these two beasts (RZ4Intuen and RZ4CM) for a long time... SWId does no longer exists, so I have to find another way to detect the updates....

**Comment by grantemsley** [comment]
Strangely swid does report a proper value in the getsoftwares api call. It's only the catalog where it's sometimes missing.

**Comment by dssantos83** [comment]
Hello guys. Same problem here. After the @rzander update (https://github.com/rzander/ruckzuck/releases/tag/1.7.2.5) the download and deployment started to work again. But now I have a lot of bugs on packages updates. Gone crazy :(

**Comment by rzander** [comment]
I have update the RZ4CM.exe on https://github.com/rzander/ruckzuck/releases/tag/1.7.2.5
The Update detection will no longer use the SWId. If the RuckZuck package does not conatin an RZID (all new Packages), it will generate an RZID based on the ModifyDate from the RZCatalog...

**Comment by grantemsley** [comment]
Finally got a chance to test out the update. So far so good, it looks like it properly created all the packages I had issues with before.  It's still showing the oldest installed version under old version instead of the newest installed one, but it looks like detection is working properly so that's just a display bug and doesn't really matter.

Thanks for the quick work fixing it!

**Comment by dssantos83** [comment]
I've tested here too. Everything is working as expected. Thanks for the fix.

**Comment by rzander** [comment]
FYI, on https://github.com/rzander/ruckzuck/releases/tag/1.7.2.5 there is a updated RZ4CM.exe that fixes an Issue when you try to edit an app.  The installer (RZ4ConfigMgrSetup.exe) will be updated with the next version.
