### ISSUE TITLE
RZGet closes immediately

### ISSUE THREAD

**Issue by johnfromstatefarm** [rzander/ruckzuck#210]
Hello, whenever I open RZGet.exe, either with admin or no admin, it opens CMD and then closes it immediately. Is this normal behavior? I want to start utilizing the install command since this seems like a great alternative to Chocolatey, and the UI version of the app seems to be broken and will randomly stop installing programs. Thank you.

**Comment by rzander** [comment]
RZGet is a Console-Application. You must start this tool from CMD or PowerShell console. If you are on the latest W11 build, you can drag&drop RZGet.exe into a PowerShell Terminal... otherwise start CMD or PowerShell and start RZGet.exe from there. 
If you do not specify any parameters, it will show you all available parameters.
