### ISSUE TITLE
Missing Software-Items

### ISSUE THREAD

**Issue by jakmit** [rzander/ruckzuck#224]
When clicking on "Create new Software-Item" there aren't shown any existing installations.

**Comment by rzander** [comment]
Do you have any ? Press and hold [shift] while selecting "Create new Software-Item" ... this should show Items that are already in RuckZuck...

**Comment by jakmit** [comment]
no, just empty gray. above is standing "missing software-items:"

**Comment by rzander** [comment]
On a single computer or on multiple computers? Any apps with special characters in the name installed ? 
Do you see all your software in appwiz.cpl ?

**Comment by jakmit** [comment]
I'm using RuckZuck for Intune on our school's computers and never had a problem.
Tested running it on multiple PCs and always the same issue, no problems showing up when clicking on create software item.

what is appwiz.cpl?

**Comment by rzander** [comment]
So the Problem is with "RZ4Intune.exe" ? Then it's clear, you cannot create RuckZuck Packages with RZ4Intune.exe you have to use RuckZuck.exe ... I have to remove this button from RZ4Intune...
Just run "appwiz.cpl" (press Windows + "r" , paste "appwiz.cpl" and press enter)... its the Control Panel applet to show installed software...

**Comment by jakmit** [comment]
Works for me now, thank you!
