### ISSUE TITLE
Possible to detect version from DisplayName if DisplayVersion is not set?

### ISSUE THREAD

**Issue by slycordinator** [rzander/ruckzuck#250]
This is an edge case, but occasionally an installer does not set DisplayVersion, while the version information is available in the DisplayName.

Would it be possible to change RuckZuck to extract the version information from the DisplayName in such a situation?

For example:
I have Simple Sticky Notes installed (from https://www.simplestickynotes.com/ )
In the registry for it, DisplayName is 'Simple Sticky Notes 6.3' and DisplayVersion is unset.

And then in RuckZuck, it always shows an update available with:
New Version: 6.3 Old Version: [blank]

Now, I know I can have it ignore, which is a workaround, but maybe we should consider checking DisplayName for the version if it's not found otherwise.

Thanks

Note: I emailed the devs to ask them to set DisplayVersion, but I received no reply.

**Comment by rzander** [comment]
If you just look on "Sticky Notes", then it looks very easy to get the version from the DisplayName.... But in general, it's nearly not possible because there are so many different ways vendors can create theirs ProductNames. E.g. some Vendors have a different Version in the ProductName than in the ProductVersion, some do not follow the semantic version schema etc.

If you install "Simple Sticky Notes" with RuckZuck, the Package will register the File-Version of the executable as ProductVersion
![image](https://github.com/rzander/ruckzuck/assets/11909453/6775a7e6-9668-4fc7-baaf-9400f4dac39c)
... so you will no longer prompted for an update und further versions will be detected properly...

Maybe you should contact the Vendor of the Tool, to register a proper ProductVersion ...
