### ISSUE TITLE
Detection scripts should not hard-code the latest product version

### ISSUE THREAD

**Issue by sschuberth** [rzander/ruckzuck#27]
E.g. the current detection script for Sublime Text 3 is

```
if ((Get-ItemProperty -path 'HKLM:\SOFTWARE\MICROSOFT\WINDOWS\CURRENTVERSION\UNINSTALL\SUBLIME TEXT 3_IS1' -Name DisplayVersion -ea SilentlyContinue | Select-Object -exp DisplayVersion) -eq '3.0.3176') { return $true } else { 
    if ((Get-ItemPropertyValue -path 'HKLM:\SOFTWARE\MICROSOFT\WINDOWS\CURRENTVERSION\UNINSTALL\SUBLIME TEXT 3_IS1' -Name DisplayName -ea SilentlyContinue) -eq 'Sublime Text Build 3176') {
        New-ItemProperty -Path 'HKLM:\SOFTWARE\MICROSOFT\WINDOWS\CURRENTVERSION\UNINSTALL\SUBLIME TEXT 3_IS1' -Name DisplayVersion -PropertyType String -Value '3.0.3176'; return $true
    } else {  return $false }
}
```

It seems that the currently latest product version (`3.0.3176` in my case) is inlined / hard-coded here. That's confusing when sharing detection scripts separately with other PCs. My proposal would be to use a variable like `$latestVersion` instead.

**Comment by rzander** [comment]
Sublime is a bad example and Special because the setup does not write a DisplayVersion... 

If you update the Product Version in RuckZuck.exe,  it will automatically update the detection script to use the specified Version...

There are tools like RuckZuck for Configuration Manager which are using the dection script in a separate powershell instance.  This would make it difficult if you are referenceing a variable for the latest version.

I don't see a real benefit here...

**Comment by sschuberth** [comment]
> I don't see a real benefit here...

I have to admit the benefit is less than I though originally, because I was thinking at first that hard-coded version is the installed version, not the latest version.
