### ISSUE TITLE
Some minior GUI improvements suggestions

### ISSUE THREAD

**Issue by ltGuillaume** [rzander/ruckzuck#58]
1. Double-click an item to queue for installation
2. Add Favorites ->Most Downloads (or "Popular Software")
3. The icon resizing looks like it uses a simple nearest-neighbor algorithm, which makes some icons look jagged. Maybe you can apply some bicubic algorithm to properly resize them?
4. Why is there a disabled toolbar customization button next to the Favorites button?

**Comment by rzander** [comment]
4 Topics in one request :-( ... For change tracking it's easier to have separate "Issues"...

1. Double-click an item to queue for installation
   **I do not agree on this, it can be dangerous if a double click triggers an installation**
2. Add Favorites ->Most Downloads (or "Popular Software")
    **What is your definition of "Popular" ? Just counting downloads will be useless as Enterprise Software will have much more downloads than SW for personal use...**
3. The icon resizing looks like it uses a simple nearest-neighbor algorithm, which makes some icons look jagged. Maybe you can apply some bicubic algorithm to properly resize them?
  **Can you make some examples of "bad" icons please ?! Most Products have a 128px * 128px logo but there are SW where the vendor only provides a e.g. 32px * 32px logo...** 
4. Why is there a disabled toolbar customization button next to the Favorites button?
**I never had a problem with that :-) Fixed: https://github.com/rzander/ruckzuck/commit/c4ef033dab261064fab57233a18cf3d8991f3597**

**Comment by ltGuillaume** [comment]
1. Fair enough 😃
2. Good point, but I just meant "ordered by number of downloads", yeah. Wouldn't really care if the first bunch would consist of enterprise software only.
3. I actually meant the icons that have been uploaded in a "high" resolution, such as 256x256px.
![image](https://user-images.githubusercontent.com/4777345/66854770-4261bf80-ef82-11e9-87e8-759acf976b17.png) ![image](https://user-images.githubusercontent.com/4777345/66854927-95d40d80-ef82-11e9-822d-f1111c462d03.png) ![image](https://user-images.githubusercontent.com/4777345/66854970-ab493780-ef82-11e9-8644-73e6780226a5.png) ![image](https://user-images.githubusercontent.com/4777345/66855028-c74cd900-ef82-11e9-846c-5ee977da6587.png) ![image](https://user-images.githubusercontent.com/4777345/66855212-24e12580-ef83-11e9-9cef-ef886c890e90.png) ![image](https://user-images.githubusercontent.com/4777345/66855256-34606e80-ef83-11e9-9d5f-13963fbce08a.png)
With a proper resizing algorithm, they wouldn't all look like they were resized by Paint in W95 😆

4. Cool

**Comment by rzander** [comment]
2. Top 20 is currently:

Downloads | ShortName
-- | --
7323 | VCRedist2013x64
7166 | VCRedist2013x86
2350 | VCRedist2012x86
2257 | VCRedist2012x64
2054 | WinPcap
1989 | VCRedist2017x64
1835 | VCRedist2010x86
1810 | 7-Zip
1780 | VCRedist2019x86
1749 | VCRedist2019x64
1650 | JavaRuntime8
1474 | VCRedist2010x64
1452 | JavaRuntime8x64
1385 | VLC
1360 | 7-Zip(MSI)
1226 | ConfigMgrTools
1148 | VSTO2010
1024 | Silverlight
908 | RuckZuck
784 | WinDirStat

I don't think this will change frequently.. some SW has a high count because it's old and never updated... On the other side, AdobeReaderDC was updated two hours ago and has a DL count of 300+ but it's not part of the list.  I am not convinced yet, if it makes sense to just count downloads...

3. Ok, agree, downscaling can be optimized... RuckZuck.exe does get the Images directly from the REST API; so I'm thinking of an option that the tool can request a size (e.g. 32px * 32px ) and the REST API is doing the sizing. -> More CPU load on the backend 👎  + less network traffic as images are reduced 👍 ...

**Comment by ltGuillaume** [comment]
2. Ah ok, I see your point now with all the runtime distributables 😆

3. Makes sense. I don't know if RuckZuck.exe is DPI-aware and thus that the icon size differs (in the list), otherwise the 32x32px resized images could simply be pregenerated once on the server. CPU load would effectively stay the same.

**Comment by rzander** [comment]
Server Option to GetIcon with a specific size: https://github.com/rzander/ruckzuck/commit/60e3617ee2e6ff7c407a0002018a8c0b3011ada7
It's not yet online as i want to do some more tests...  I'm using https://docs.sixlabors.com/api/index.html to resize images.
