### ISSUE TITLE
Application Folder Naming Convention

### ISSUE THREAD

**Issue by subiera** [rzander/ruckzuck#6]
Before anything, awesome work and thank you for developing this tool. It resolves a major shortcoming.

General question(s):

 - Why do application content folders include what appears to be the same content included in the Optional Reference field of an application ("RZXXXXX") in their name?

 - What is it's purpose?

 - Also, is there any way to exclude that reference from the folder naming convention?

**Comment by rzander** [comment]
Some Software-Vendors do update their Products without changing the version... A RuckZuck package can also have multiple "Deployment Types" with different content. E.g there are some Packages with different content for Win7, Win8 etc. and all these "Deployment Types" requires a unique source Folder...
That's why RuckZuck requires an Identifier for the products an that's the RZxxxxx number...

You can rename the content folder if you want...  but what is the Problem with the ID? End-Users will not see this ID anyway...

**Comment by boivinx7** [comment]
Hi, I would like to say that I love all your work.
I have a Question as for Naming convention of Folders, App and Collection
I Use
For Folders:
Company
              |
              Software_Version
                                         |
                                         Architecture_Language

For Collections and Apps:
Company_ Software_Version

For Deployment Types
Company_ Software_Version_Architecture_Language

Is it possible to do something to customize that
I dont Mind the RZ ID at the And, could be usefull. But it would be great if I could customize it.
For Now I create the App check the Detection methode then I delete everything, the collection and the app. And redoo everything.
Also is there a way to not create the collection I have a tool for that already.
Thank you
