### ISSUE TITLE
Questions and feedback

### ISSUE THREAD

**Issue by AlehKliauzo** [rzander/ruckzuck#71]
Hi, I've been working on integrating RuckZuck repo in SCCM Importer and have some questions and feedback.

1. I've noticed that install script is split into 3 parts (PSPreInstall, PSInstall, PSPostInstall), 2 of which are optional. The actual install script is created by joining them.
https://github.com/rzander/ruckzuck/blob/0eb0b915387bc5b6d09fd3fa137ce3e1eea6a9e3/RZ4CM/CM_API.cs#L1105-L1124
What's the logic behind this, why not just send complete script as PSInstall and remove 2 optional properties?
2. Seems like PSPreReq is used mostly to add 64-bit OS deployment requirements in RZ4CM 
https://github.com/rzander/ruckzuck/blob/0eb0b915387bc5b6d09fd3fa137ce3e1eea6a9e3/RZ4CM/CM_API.cs#L1168-L1194
I think in 99% of cases it contains "[Environment]::Is64BitProcess" for 64-bit software and "$true" for 32-bit software. Wouldn't it make more sense to do these checks based on Architecture property? (I haven't checked source code/usage of PSPreReq in other projects)
3. Many files have X509 as HashType, but it's not a file hash, it's a certificate hash. A good example here is "Windows Assessment and Deployment Kit - Windows 10" - it has 2 files that have the same X509 hash because they are signed by the same certificate, however they are different files. In essence we end up checking whether file was signed with certificate we expect it to be signed, instead of checking file integrity.
4. There are many files that have "HashType": null, but contain valid MD5 hash in "FileHash" property.
5. Currently the only way to get download size without downloading software is to send a HEAD request to file URL and check Content-Length in reponse headers. Would be great if download size was part of catalog and software info JSONs.
6. Looks like SWid are changed with each new version of software, which is fine, but not what I expected. One needs to check how JSONs change over time to find out that SWid changes with updates. And for some properties one needs to go through RuckZuck source code to figure out their purpose (PSPreInstall, PSPostInstall, PSPreReq). Would be great if REST API wiki mentioned not only how to interact with API, but also what's the purpose of some properties and how they behave.
7. 2 packages ("Adobe Acrobat Reader DC" and "Adobe Acrobat Reader DC MUI") have "UpdateX64" as Architecture, shouldn't it be "X64"?

**Comment by rzander** [comment]
So many questions in on e request ... 
1. Agree, but it can be helpful in an automation scenario where customers want to add specific postinstall scripts ( e.g. set in internal registry key ). 
2. The *Architecture* property has a wrong Name, it should be called *InstallationType* as it's not only related to the Architecture. I may have to change that in the next versions. 
RuckZuck Applications can have multiple *InstallationTypes* (see your question 7, AdobeReader is an example), so if you edit an Application with RuckZuck.exe or RZ4CM.exe it just shows you the JSON for the first *InstallationType* that matches the PreRequisite Rules. Example: if you have AdobeReaerinstalled it will show you the *UpdateX64* JSON where it's only downloading the MSP File... 
Back to your Question: Most apps have [Environment]::Is64BitProcess as PreReq because the detection script is x64 related. It does not mean that the App is X64. Some detection scripts are independant of the architecture (e.g. most MSI pacakges) so they get a $true as they can work on both platforms.
If ConfigMgr would allow PowerShell scripts as Requirement Rules (like Intune), it would be no problem... But today, there is no proper way to parse a PowerShell script into ConfigMgr Requirement Rules.
3. That's why it's called X509... But agree that it does not check if the X509 signature is valid. Can you open a **separate Issue**, so I can track it as a Feature request for the next version?
4. These must be older Packages, where all Hashes where MD5. Do you have some Examples of newer Packages with HashType:null ?
5. Can you make a **separate Issue** for that ?
6. SWID is a historical attribute which is only used in RZ4CM and RZ4Intune to have a short unique identifier... You can be luck that there is a wiki page ;-) ... Once I find some time, I will start document everything...  Or maybe *someone else* has time to do it...
7. see question 2

**Comment by AlehKliauzo** [comment]
1, 2 & 7. That makes sense now. Thanks for the explanation.
3. Done
4. I've right now checked info on all software that's returned by catalog request:
	516 total packages
	518 total files
	364 files with HastType X509
	100 files with HastType MD5
	54 files with HastType null
5. Done
6. Gotcha, I'll see if I can do it next week.
