### ISSUE TITLE
RZ4Intune Invoke-Webrequest Failed

### ISSUE THREAD

**Issue by ftucho** [rzander/ruckzuck#93]
Invoke-Webrequest failed if Internet Explorer first-launch wizard not run.
RZ4Intune.ps1:1242
Invoke-WebRequest): "The response content cannot be parsed because the Internet Explorer engine is not available, or Internet Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again. "

After starting and closing IE before running RZ4Intune the command succeeds.

**Comment by rzander** [comment]
I think this is no longer the case on the current windows builds...

**Comment by Edocsyl** [comment]
Hi, this is still a case on Windows 20H2. There is also a reason why this happens. 

I seems to change the line in RZ4Intune.ps1 from:

`$img = [Convert]::ToBase64String((Invoke-WebRequest "$($rzSW.iconURL)&size=128").Content)`

to: 

`$img = [Convert]::ToBase64String((Invoke-WebRequest -Uri "$($rzSW.iconURL)&size=128" -UseBasicParsing).Content)
`
But i could not test it. 

I found this: https://stackoverflow.com/questions/38005341/the-response-content-cannot-be-parsed-because-the-internet-explorer-engine-is-no
