### ISSUE TITLE
Updates Calibre x64 with x86

### ISSUE THREAD

**Issue by truthsword** [rzander/ruckzuck#98]
Identified Calibre x64 for update, but installed the x86 package, leaving me with two Calibre installations.

How to force x64 update package?

**Comment by rzander** [comment]
1. "Someone" has to update/create a calibre Package with the x64 MSI instead of the X86
2. It was the decision of the Software Vendor to allow a parallel installation of X86 and X64 calibre. when creating a x64 ruckzuck package, it's possible to remove the x86 msi by using some PowerShell logic to figure out the uninstall string for the x86 version...
3. We can remove the x64 version from getting updates, which is also not a final solution...

I understand that the current result is not user friendly... I'm not using calibre; are there any benefits of using X64 vs X86? would you recommend to update all x86 version to x64? should we manage two packages x86 and x64 ?

**Comment by truthsword** [comment]
Thanks for your response.
1. Obviously, I'm don't know what that means; 2, 3... no comment

> are there any benefits of using X64 vs X86? 

I don't know. Presumably, the developer thought so, else they would not have expended the effort to develop an x64 package.

> would you recommend to update all x86 version to x64? 

Well... we can't replace x86 with x64 in all machines.

> should we manage two packages x86 and x64 ?

That's not my call, but if we should have a means to exclude x64 installs from updating if the update will only add an x86 install. How that is best implemented, I'm unsure.

I just started using this program, so weigh my comments accordingly.

**Comment by rzander** [comment]
as the current package is X86, I've changed the package to remove all existing x64 versions after installation.
With a new version of calibre, the author of the package can then decide to use the x86 or x64 version (or both)... but x64 would only run on x64 devices and x86 would run on both platforms...

**Comment by rzander** [comment]
The RuckZuck Package "calibre" contains now the x86 and the x64 architecture... on a x64 device, it will install the x64 Version.

**Comment by truthsword** [comment]
Good to know. I tried to upload the calibre x64 package (along with cryptomator), but that app has no upload confirmation, so I was unsure whether it was transmitted.

**Comment by rzander** [comment]
You can enter your eMaill address in the "Author" attribute to allow me to send feedback. The Attribute is automatically cleaned when the package is approved.
If the "upload" button get's greyed out after uploading, your request is in the queue. As long as it's not approved, you can modify by uploading it again (change the File-Url to activate the "upload" button).
Cryptomator was a bit tricky, because it does requires "Dokan" as prerequisite... and "Dokan" requires VCredist2019...
